// IATA airline code → name mapping for the marquee strip
export interface Airline {
  code: string;
  name: string;
}

export const AIRLINES: Airline[] = [
  { code: "0b", name: "Blue Air" },
  { code: "1l", name: "Open Skies" },
  { code: "2d", name: "Eastern Airlines" },
  { code: "2i", name: "Star Peru" },
  { code: "2j", name: "Air Burkina" },
  { code: "2k", name: "Aviandina" },
  { code: "2m", name: "Maya Island Air" },
  { code: "2t", name: "TruJet" },
  { code: "3k", name: "Jetstar Asia" },
  { code: "3m", name: "Silver Airways" },
  { code: "3o", name: "Air Arabia Maroc" },
  { code: "3u", name: "Sichuan Airlines" },
  { code: "4c", name: "LATAM Colombia" },
  { code: "4m", name: "LATAM Argentina" },
  { code: "4n", name: "Air North" },
  { code: "4z", name: "Airlink" },
  { code: "5f", name: "Fly One" },
  { code: "5j", name: "Cebu Pacific" },
  { code: "5u", name: "TAG Airlines" },
  { code: "5w", name: "Astraeus" },
  { code: "5z", name: "Cemair" },
  { code: "6e", name: "IndiGo" },
  { code: "6j", name: "Solaseed Air" },
  { code: "7c", name: "Jeju Air" },
  { code: "7h", name: "Ravn Alaska" },
  { code: "8d", name: "FitsAir" },
  { code: "8m", name: "Myanmar Airways International" },
  { code: "8p", name: "Pacific Coastal Airlines" },
  { code: "9c", name: "Spring Airlines" },
  { code: "9m", name: "Central Mountain Air" },
  { code: "9n", name: "Tropic Air" },
  { code: "9u", name: "Air Moldova" },
  { code: "9v", name: "Avior Airlines" },
  { code: "9x", name: "Southern Air Charter" },
  { code: "a1", name: "APG Airlines" },
  { code: "a3", name: "Aegean Airlines" },
  { code: "a5", name: "HOP!" },
  { code: "aa", name: "American Airlines" },
  { code: "ac", name: "Air Canada" },
  { code: "ad", name: "Azul" },
  { code: "af", name: "Air France" },
  { code: "ah", name: "Air Algérie" },
  { code: "ai", name: "Air India" },
  { code: "ak", name: "AirAsia" },
  { code: "am", name: "Aeroméxico" },
  { code: "an", name: "Advanced Air" },
  { code: "ar", name: "Aerolíneas Argentinas" },
  { code: "as", name: "Alaska Airlines" },
  { code: "at", name: "Royal Air Maroc" },
  { code: "av", name: "Avianca" },
  { code: "aw", name: "Africa World Airlines" },
  { code: "ay", name: "Finnair" },
  { code: "az", name: "ITA Airways" },
  { code: "b0", name: "La Compagnie" },
  { code: "b6", name: "JetBlue" },
  { code: "b7", name: "UNI Air" },
  { code: "ba", name: "British Airways" },
  { code: "bc", name: "Skymark Airlines" },
  { code: "bf", name: "French Bee" },
  { code: "bg", name: "Biman Bangladesh Airlines" },
  { code: "bi", name: "Royal Brunei Airlines" },
  { code: "bp", name: "Air Botswana" },
  { code: "br", name: "EVA Air" },
  { code: "bs", name: "US-Bangla Airlines" },
  { code: "bt", name: "airBaltic" },
  { code: "bx", name: "Air Busan" },
  { code: "ca", name: "Air China" },
  { code: "cd", name: "Corendon Dutch Airlines" },
  { code: "ci", name: "China Airlines" },
  { code: "cl", name: "Lufthansa CityLine" },
  { code: "cm", name: "Copa Airlines" },
  { code: "cx", name: "Cathay Pacific" },
  { code: "cy", name: "Cyprus Airways" },
  { code: "cz", name: "China Southern Airlines" },
  { code: "d8", name: "Norwegian Air International" },
  { code: "dd", name: "Nok Air" },
  { code: "de", name: "Condor" },
  { code: "dg", name: "Cebgo" },
  { code: "dl", name: "Delta Air Lines" },
  { code: "dm", name: "Arajet" },
  { code: "dt", name: "TAAG Angola Airlines" },
  { code: "dy", name: "Norwegian" },
  { code: "e5", name: "Air Arabia Egypt" },
  { code: "e9", name: "Evelop Airlines" },
  { code: "ec", name: "EasyFly" },
  { code: "ei", name: "Aer Lingus" },
  { code: "ek", name: "Emirates" },
  { code: "en", name: "Air Dolomiti" },
  { code: "et", name: "Ethiopian Airlines" },
  { code: "ew", name: "Eurowings" },
  { code: "ey", name: "Etihad Airways" },
  { code: "f3", name: "Flyadeal" },
  { code: "f8", name: "Flair Airlines" },
  { code: "f9", name: "Frontier Airlines" },
  { code: "fa", name: "FlySafair" },
  { code: "fb", name: "Bulgaria Air" },
  { code: "fd", name: "Thai AirAsia" },
  { code: "fi", name: "Icelandair" },
  { code: "fj", name: "Fiji Airways" },
  { code: "fm", name: "Shanghai Airlines" },
  { code: "fn", name: "Fastjet" },
  { code: "fr", name: "Ryanair" },
  { code: "fz", name: "Flydubai" },
  { code: "g3", name: "Gol" },
  { code: "g4", name: "Allegiant Air" },
  { code: "g9", name: "Air Arabia" },
  { code: "ga", name: "Garuda Indonesia" },
  { code: "ge", name: "TransAsia Airways" },
  { code: "gf", name: "Gulf Air" },
  { code: "gk", name: "Jetstar Japan" },
  { code: "gl", name: "Air Greenland" },
  { code: "gp", name: "APG Airlines" },
  { code: "gq", name: "Sky Express" },
  { code: "h1", name: "Hahn Air" },
  { code: "h2", name: "Sky Airline" },
  { code: "h4", name: "HiSky" },
  { code: "h5", name: "Fly540" },
  { code: "h7", name: "Eagle Air Iceland" },
  { code: "h8", name: "Latin American Wings" },
  { code: "ha", name: "Hawaiian Airlines" },
  { code: "hc", name: "Air Senegal" },
  { code: "hf", name: "TUIfly" },
  { code: "hm", name: "Air Seychelles" },
  { code: "hr", name: "Hahn Air" },
  { code: "hu", name: "Hainan Airlines" },
  { code: "hv", name: "Transavia" },
  { code: "hx", name: "Hong Kong Airlines" },
  { code: "hy", name: "Uzbekistan Airways" },
  { code: "ia", name: "Iraqi Airways" },
  { code: "ib", name: "Iberia" },
  { code: "id", name: "Batik Air" },
  { code: "ij", name: "Spring Japan" },
  { code: "it", name: "Tigerair Taiwan" },
  { code: "iu", name: "Super Air Jet" },
  { code: "ix", name: "Air India Express" },
  { code: "iz", name: "Arkia" },
  { code: "j2", name: "Azerbaijan Airlines" },
  { code: "j9", name: "Jazeera Airways" },
  { code: "ja", name: "JetSMART" },
  { code: "jd", name: "Beijing Capital Airlines" },
  { code: "jj", name: "JetSMART Peru" },
  { code: "jl", name: "Japan Airlines" },
  { code: "jm", name: "Jambojet" },
  { code: "jp", name: "Adria Airways" },
  { code: "jq", name: "Jetstar" },
  { code: "jt", name: "Lion Air" },
  { code: "ju", name: "Air Serbia" },
  { code: "jx", name: "Starlux Airlines" },
  { code: "jy", name: "interCaribbean Airways" },
  { code: "jz", name: "Skyways Express" },
  { code: "k6", name: "Cambodia Angkor Air" },
  { code: "ka", name: "Cathay Dragon" },
  { code: "kc", name: "Air Astana" },
  { code: "ke", name: "Korean Air" },
  { code: "kg", name: "Key Lime Air" },
  { code: "kk", name: "AtlasGlobal" },
  { code: "kl", name: "KLM" },
  { code: "km", name: "Air Malta" },
  { code: "kp", name: "ASKY Airlines" },
  { code: "kq", name: "Kenya Airways" },
  { code: "ku", name: "Kuwait Airways" },
  { code: "kx", name: "Cayman Airways" },
  { code: "la", name: "LATAM Airlines" },
  { code: "lf", name: "Contour Airlines" },
  { code: "lg", name: "Luxair" },
  { code: "lh", name: "Lufthansa" },
  { code: "lj", name: "Jin Air" },
  { code: "lm", name: "Loganair" },
  { code: "lo", name: "LOT Polish Airlines" },
  { code: "lp", name: "LATAM Peru" },
  { code: "lr", name: "Avianca Costa Rica" },
  { code: "lx", name: "SWISS" },
  { code: "ly", name: "El Al" },
  { code: "md", name: "Air Madagascar" },
  { code: "me", name: "Middle East Airlines" },
  { code: "mf", name: "Xiamen Airlines" },
  { code: "mh", name: "Malaysia Airlines" },
  { code: "mk", name: "Air Mauritius" },
  { code: "mm", name: "Peach Aviation" },
  { code: "mo", name: "Calm Air" },
  { code: "ms", name: "EgyptAir" },
  { code: "mu", name: "China Eastern Airlines" },
  { code: "mx", name: "Breeze Airways" },
  { code: "n0", name: "Norse Atlantic Airways" },
  { code: "n3", name: "Omni Air International" },
  { code: "nh", name: "ANA" },
  { code: "nk", name: "Spirit Airlines" },
  { code: "no", name: "Neos" },
  { code: "np", name: "Nile Air" },
  { code: "nt", name: "Binter Canarias" },
  { code: "nx", name: "Air Macau" },
  { code: "nz", name: "Air New Zealand" },
  { code: "oa", name: "Olympic Air" },
  { code: "ob", name: "Boliviana de Aviación" },
  { code: "od", name: "Batik Air Malaysia" },
  { code: "og", name: "PLAY" },
  { code: "ok", name: "Czech Airlines" },
  { code: "om", name: "MIAT Mongolian Airlines" },
  { code: "or", name: "TUI fly Netherlands" },
  { code: "os", name: "Austrian Airlines" },
  { code: "ou", name: "Croatia Airlines" },
  { code: "ow", name: "Skyward Express" },
  { code: "oz", name: "Asiana Airlines" },
  { code: "p5", name: "Copa Airlines Colombia" },
  { code: "pa", name: "Airblue" },
  { code: "pc", name: "Pegasus Airlines" },
  { code: "pd", name: "Porter Airlines" },
  { code: "pg", name: "Bangkok Airways" },
  { code: "pk", name: "PIA" },
  { code: "pr", name: "Philippine Airlines" },
  { code: "pu", name: "Plus Ultra" },
  { code: "pw", name: "PrecisionAir" },
  { code: "px", name: "Air Niugini" },
  { code: "py", name: "Surinam Airways" },
  { code: "pz", name: "Voepass" },
  { code: "q4", name: "Masrik Air" },
  { code: "q6", name: "Volaris Costa Rica" },
  { code: "qf", name: "Qantas" },
  { code: "qg", name: "Citilink" },
  { code: "qp", name: "Akasa Air" },
  { code: "qr", name: "Qatar Airways" },
  { code: "qs", name: "SmartWings" },
  { code: "qv", name: "Lao Airlines" },
  { code: "qz", name: "Indonesia AirAsia" },
  { code: "rj", name: "Royal Jordanian" },
  { code: "ro", name: "TAROM" },
  { code: "rq", name: "Kam Air" },
  { code: "s4", name: "Azores Airlines" },
  { code: "s6", name: "SalamAir" },
  { code: "s7", name: "S7 Airlines" },
  { code: "sa", name: "South African Airways" },
  { code: "sb", name: "Air Calin" },
  { code: "sc", name: "Shandong Airlines" },
  { code: "sg", name: "SpiceJet" },
  { code: "sk", name: "SAS" },
  { code: "sl", name: "Thai Lion Air" },
  { code: "sn", name: "Brussels Airlines" },
  { code: "sq", name: "Singapore Airlines" },
  { code: "ss", name: "Corsair" },
  { code: "su", name: "Aeroflot" },
  { code: "sv", name: "Saudia" },
  { code: "sy", name: "Sun Country Airlines" },
  { code: "sz", name: "Somon Air" },
  { code: "t3", name: "Eastern Airways" },
  { code: "t5", name: "Turkmenistan Airlines" },
  { code: "ta", name: "TACA" },
  { code: "tb", name: "TUI fly Belgium" },
  { code: "tc", name: "Air Tanzania" },
  { code: "tg", name: "Thai Airways" },
  { code: "tj", name: "Tradewind Aviation" },
  { code: "tk", name: "Turkish Airlines" },
  { code: "tm", name: "LAM Mozambique Airlines" },
  { code: "tn", name: "Air Tahiti Nui" },
  { code: "to", name: "Transavia France" },
  { code: "tp", name: "TAP Air Portugal" },
  { code: "tr", name: "Scoot" },
  { code: "ts", name: "Air Transat" },
  { code: "tu", name: "Tunisair" },
  { code: "tw", name: "T'way Air" },
  { code: "tx", name: "Air Caraïbes" },
  { code: "u2", name: "easyJet" },
  { code: "u4", name: "Buddha Air" },
  { code: "u5", name: "USA Jet Airlines" },
  { code: "ua", name: "United Airlines" },
  { code: "uk", name: "Vistara" },
  { code: "ul", name: "SriLankan Airlines" },
  { code: "uo", name: "Hong Kong Express" },
  { code: "up", name: "Bahamasair" },
  { code: "uu", name: "Air Austral" },
  { code: "ux", name: "Air Europa" },
  { code: "v0", name: "Conviasa" },
  { code: "v7", name: "Volotea" },
  { code: "va", name: "Virgin Australia" },
  { code: "vb", name: "Viva Aerobus" },
  { code: "ve", name: "EasyFly" },
  { code: "vf", name: "Valuejet" },
  { code: "vn", name: "Vietnam Airlines" },
  { code: "vs", name: "Virgin Atlantic" },
  { code: "vt", name: "Air Tahiti" },
  { code: "vy", name: "Vueling" },
  { code: "vz", name: "Thai VietJet Air" },
  { code: "w3", name: "Arik Air" },
  { code: "w4", name: "LC Perú" },
  { code: "w6", name: "Wizz Air" },
  { code: "w9", name: "Wizz Air UK" },
  { code: "wf", name: "Widerøe" },
  { code: "wg", name: "Sunwing Airlines" },
  { code: "wj", name: "Green Africa Airways" },
  { code: "wm", name: "Winair" },
  { code: "wn", name: "Southwest Airlines" },
  { code: "ws", name: "WestJet" },
  { code: "wy", name: "Oman Air" },
  { code: "x1", name: "Hahn Air Technologies" },
  { code: "xk", name: "Air Corsica" },
  { code: "xl", name: "LATAM Ecuador" },
  { code: "xp", name: "Xtra Airways" },
  { code: "xq", name: "SunExpress" },
  { code: "xy", name: "flynas" },
  { code: "xz", name: "Congo Airways" },
  { code: "y4", name: "Volaris" },
  { code: "yp", name: "Air Premia" },
  { code: "yw", name: "Air Nostrum" },
  { code: "z0", name: "TAG Airlines" },
  { code: "z2", name: "Philippines AirAsia" },
  { code: "zg", name: "ZIPAIR" },
  { code: "zh", name: "Shenzhen Airlines" },
  { code: "zl", name: "Regional Express" },
];
